### PR TITLE
[FixBug][seatunnel-web]Fix delete job task

### PR DESCRIPTION
**Pull request by zhibinF**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
Fixed an issue where the jobdefinition was deleted but the job task was not deleted

### CODE REVIEW

**Comment by XiaoJiang521** [comment]
Please add a screenshot of the test passing

**Comment by zhibinF** [comment]
image

**Comment by zhibinF** [comment]
image
image
image
image

**Review by XiaoJiang521 — APPROVED** [review]

**Comment by XiaoJiang521** [comment]
LGTM

**Review by EricJoy2048 — APPROVED** [review]

**Pull request merged**
