### PR TITLE
[Improve][feature][Bug] Add Tooltip and  Fix Design Issue In the Task Definition

### PR DESCRIPTION
**Pull request by SachinS10-lab**
### [Bug]
When screen height is reduced or more items added in the task synchronization definition sidebar, tiles are falls out of the task synchronization definition sidebar.

Screenshot 2024-08-02 at 11 11 33 AM

## Purpose of this pull request
This PR aims to enhance user experience by improving navigation through the task synchronization process and Fixed the above mentioned bug.

**Changes Introduced:**
    Tooltips for Task Tiles : Added tooltips to the Source, Sink, and Transform tiles in the task synchronization definition sidebar. The tooltips provide guidance on dragging and configuring the tiles.
    Bug Fix : Addressed a bug that affected the display of the sidebar when the screen height was reduced or when more items were added.

**How It Works:**
    Hover Over Info Icon : When hovering over the Info icon added to the right side of the task synchronization definition sidebar tiles, a tooltip will appear with helpful instructions.
    After Dragging Tiles : When dragging Source, Sink, or Transform tiles onto the canvas and selecting them, hovering over the tile will display a tooltip with additional instructions.

**Additional Notes:**
    This is my first pull request. I would appreciate any comments, suggestions, or advice to improve it.
    
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by Hisoka-X** [comment]
cc @arshadmohammad

**Comment by SachinS10-lab** [comment]
Hi @Hisoka-X,
I'm unable to address this Issue. Could please explain what is happening? How Can I Overcome this Issue?


cc @arshadmohammad

**Comment by Hisoka-X** [comment]
Please try merge from dev.

**Comment by SachinS10-lab** [comment]
Hi @Hisoka-X, I've merged from main. Could you please rerun the checks.

**Comment by SachinS10-lab** [comment]
Thanks @Hisoka-X

**Comment by arshadmohammad** [comment]
Thanks @SachinS10-lab for raising this PR. I will review it.
Meanwhile can you please remove the extra commit from your PR.

**Comment by Hisoka-X** [comment]
cc @baicie

**Comment by SachinS10-lab** [comment]
@arshadmohammad. Sorry for the delay. Is it really needed to remove one commit?

**Comment by Hisoka-X** [comment]
> @arshadmohammad. Sorry for the delay. Is it really needed to remove one commit?

IMO, unnecessary. We will execute squash and merge when merge to dev.
image

**Review by arshadmohammad — APPROVED** [review]
LGTM +1

**Review by Hisoka-X — APPROVED** [review]

**Pull request merged**
