### PR TITLE
Fix bean duplication and jar version does not exist

### PR DESCRIPTION
**Pull request by xinzhuxiansheng**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Review by davidzollo — APPROVED** [review]
LGTM

**Comment by zhangchengming601** [comment]
Please pull the latest code，bean duplication has fixed

**Comment by davidzollo** [comment]
> Please pull the latest code，bean duplication has fixed

ok, @xinzhuxiansheng  thanks for your contribution, Looking forward to your deep participation.

**Comment by xinzhuxiansheng** [comment]
> > Please pull the latest code，bean duplication has fixed
> 
> ok, @xinzhuxiansheng thanks for your contribution, Looking forward to your deep participation.

@davidzollo  Thanks for your help, I will continue to follow seatunel

**Pull request closed without merging**
