### PR TITLE
[Bug] [Seatunnel-web] When job execution initialization fails, the job execution status remains unchanged.

### PR DESCRIPTION
**Pull request by arshadmohammad**
Changed the job staus to failed when job submission failed.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by arshadmohammad** [comment]
After fix, job staus is updated
image

**Comment by arshadmohammad** [comment]
image

**Review by Hisoka-X — APPROVED** [review]
Thanks @arshadmohammad

**Comment by Hisoka-X** [comment]
Please resolve conflict

**Comment by arshadmohammad** [comment]
Thank @Hisoka-X for reviewing this PR.
Resolved the conflicts.

**Review by Hisoka-X — APPROVED** [review]

**Comment by arshadmohammad** [comment]
Thanks @Hisoka-X for reviewing and merging the PR.

**Pull request merged**
