### PR TITLE
[Improve][SeaTunnel-Web] Change JobStatus to enum type to avoid hard coding

### PR DESCRIPTION
**Pull request by wuchunfu**
## Purpose of this pull request

Change JobStatus to enum type to avoid hard coding
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Please fix ci. cc @arshadmohammad

**Comment by arshadmohammad** [comment]
Many integrations will fail after this change. @wuchunfu can you the integration tests. Here is the commend to run the integration tests

./mvnw -T 1C -B verify -DskipUT=true -DskipIT=false -DSEATUNNEL_HOME=/some/path/apache-seatunnel-2.3.7 -DST_WEB_BASEDIR_PATH=seatunnel-web-dist/target/apache-seatunnel-web-1.0.2-SNAPSHOT/apache-seatunnel-web-1.0.2-SNAPSHOT

**Comment by wuchunfu** [comment]
> Many integration tests will fail after this change. @wuchunfu can you run the integration tests. Here is the command to run the integration tests
> 
> ./mvnw -T 1C -B verify -DskipUT=true -DskipIT=false -DSEATUNNEL_HOME=/some/path/apache-seatunnel-2.3.7 -DST_WEB_BASEDIR_PATH=seatunnel-web-dist/target/apache-seatunnel-web-1.0.2-SNAPSHOT/apache-seatunnel-web-1.0.2-SNAPSHOT

@arshadmohammad Are you sure? If that's the case, then there should be an issue with this CI. Can you fix the CI problem?

**Comment by wuchunfu** [comment]
image

I didn't find any problems during my testing here

**Comment by Hisoka-X** [comment]
> > Many integration tests will fail after this change. @wuchunfu can you run the integration tests. Here is the command to run the integration tests
> > ./mvnw -T 1C -B verify -DskipUT=true -DskipIT=false -DSEATUNNEL_HOME=/some/path/apache-seatunnel-2.3.7 -DST_WEB_BASEDIR_PATH=seatunnel-web-dist/target/apache-seatunnel-web-1.0.2-SNAPSHOT/apache-seatunnel-web-1.0.2-SNAPSHOT
> 
> @arshadmohammad Thank you for your review. My testing is normal. Are you sure it was caused by my changes? If that's the case, is there a problem with CI? Can you fix it?

We don't bring test case into ci at now.

**Comment by arshadmohammad** [comment]
@wuchunfu In your attached snapshot I can not see how many tests are run, how many failed or passed, can you please attach snapshot like below
image

Here I can see 42 tests are run, 0 failed, 0 error, 0 skipped.

**Comment by Hisoka-X** [comment]
> @wuchunfu In your attached snapshot I can not see how many tests are run, how many failed or passed, can you please attach snapshot like below image
> 
> Here I can see 42 tests are run, 0 failed, 0 error, 0 skipped.

Hi @arshadmohammad , does our test case should dependency mysql container? If not, let me add it into ci.

**Comment by arshadmohammad** [comment]
The integration test cases are dependent on both MySQL and the Seatunnel-Engine.
1. Runtime mysql is being added as part of https://github.com/apache/seatunnel/issues/7403 to avoid dependency on external mysql.
I will start working on this, so we can run IT test cases in CI environment.
2. Integration tests also require seatunnel-engine which should be available in CI environment.

**Comment by Hisoka-X** [comment]
>  I will start working on this, so we can run IT test cases in CI environment.

Thanks @arshadmohammad ! You can refer https://github.com/apache/seatunnel/blob/dev/.github/workflows/build_main.yml and https://github.com/apache/seatunnel/pull/5495. We implemented the logic to run CI in forked repositories so that devs can trigger CI themselves instead of maintainers manually triggering it every time.

> Integration tests also require seatunnel-engine which should be available in CI environment.


Yes, we can use github action `actions/checkout@v4`.

**Comment by wuchunfu** [comment]
> @wuchunfu In your attached snapshot I can not see how many tests are run, how many failed or passed, can you please attach snapshot like below image
> 
> Here I can see 42 tests are run, 0 failed, 0 error, 0 skipped.

image

@arshadmohammad PTAL, thanks

**Review by arshadmohammad — APPROVED** [review]
LGTM +1

**Review by Hisoka-X — APPROVED** [review]

**Pull request merged**
