### PR TITLE
[Improvement][Seatunnel-web] Support H2 database in integration tests

### PR DESCRIPTION
**Pull request by arshadmohammad**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by arshadmohammad** [comment]
integration test execution result using default h2 database
image

**Comment by arshadmohammad** [comment]
integration test execution result using mysql data by passing -DdbType=mysql
image

**Review by Hisoka-X — APPROVED** [review]

**Comment by arshadmohammad** [comment]
Thanks @Hisoka-X  for reviewing and merging this PR.

**Comment by arshadmohammad** [comment]
With the removal of the dependency on an external database, integration tests can now run using an in-memory H2 database. However, the Seatunnel distribution is still required. 
@Hisoka-X, could you provide guidance on how to run the integration tests as part of the PR CI process?

**Comment by Hisoka-X** [comment]
The test in CI in fact is trigger mvn script. Please refer https://github.com/apache/seatunnel/blob/dev/.github/workflows/backend.yml#L645

We already have some config in https://github.com/apache/seatunnel-web/blob/main/.github/workflows/backend.yml#L161
Just need add new script into `backend.yml`.

> However, the Seatunnel distribution is still required.

We can execute mvn install before test with seatunnel-web.
1. Checkout seatunnel dev branch, https://github.com/apache/seatunnel/blob/dev/.github/workflows/backend.yml#L86
2. execute mvn install and other script which execute in local before. (Like set `SEATUNNEL_HOME`)
3. Run mvn test by mvn script.
all these step can be done with github action `run` https://github.com/apache/seatunnel/blob/dev/.github/workflows/backend.yml#L315

**Pull request merged**
