### PR TITLE
[Fix]Fix the run_time calculation to account for missing days.

### PR DESCRIPTION
**Pull request by XIAOKUOAIyang**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by Hisoka-X** [comment]
cc @arshadmohammad

**Comment by arshadmohammad** [comment]
@XIAOKUOAIyang  can you attach verification snapshot

**Comment by XIAOKUOAIyang** [comment]
Before and After Correction Comparison Image.

**Comment by XIAOKUOAIyang** [comment]
Before and After Correction Comparison Image.
微信图片_20240816145504
微信图片_20240816145532

**Review by Hisoka-X — APPROVED** [review]

**Review by arshadmohammad — APPROVED** [review]
LGTM +1

**Pull request merged**
