### PR TITLE
[Bug] [Seatunnel-web] Error when conditional column is not used in SE…

### PR DESCRIPTION
**Pull request by BilwaST**
…LECT clause

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by bilst-visa** [comment]
Test Report:

job profile content with my changes:

image

**Review by arshadmohammad — APPROVED** [review]
LGTM +1

**Review by Hisoka-X — COMMENTED** [review]
I think the better place to do this thing is in https://github.com/apache/seatunnel-web/blob/d862b6110411fc7a1f9cca82c0d73724a9638f45/seatunnel-server/seatunnel-app/src/main/java/org/apache/seatunnel/app/thirdparty/datasource/impl/BaseJdbcDataSourceConfigSwitcher.java#L141
The place fine tuning source config of jdbc.

**Comment by BilwaST** [comment]
Hi @Hisoka-X 

I did not add it here as not all DataSourceConfigSwitcher extends this BaseJdbcDataSourceConfigSwitcher class. For example HiveDataSourceConfigSwitcher.

**Comment by Hisoka-X** [comment]
> Hi @Hisoka-X
> 
> I did not add it here as not all DataSourceConfigSwitcher extends this BaseJdbcDataSourceConfigSwitcher class. For example HiveDataSourceConfigSwitcher.

But the `where_condition` only worked on jdbc connector, so change it in `BaseJdbcDataSourceConfigSwitcher` is more reasonable.

**Comment by arshadmohammad** [comment]
yes, it makes better sense to put the changes in BaseJdbcDataSourceConfigSwitcher.
@BilwaST  can you raise another addendum PR

**Comment by BilwaST** [comment]
Thank you @Hisoka-X @arshadmohammad for the feedback. I have raised another PR https://github.com/apache/seatunnel-web/pull/239

**Pull request merged**
