### PR TITLE
[Bug] [Seatunnel-web] HiveJDBC should not be used as a sink datasource

### PR DESCRIPTION
**Pull request by arshadmohammad**
Removed HDBC-Hive from sink datasource list

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by arshadmohammad** [comment]
After the fix, JDBC-Hive datasource is not available in sink connector configurations

image
Even though hive-jdbc-1 and hive-jdbc-2 are available in the system, they are not available for selection in sink connector.

image

**Comment by arshadmohammad** [comment]
Hi @dragongu, Seatunnel engine and Seatunnel-web both support the Elasticsearch sink. 
Please verify the functionality to ensure it is working correctly. If you identify any issues, kindly log a bug report and, if possible, provide a fix.

**Comment by arshadmohammad** [comment]
@Hisoka-X  can you review and merge this and other PRs

**Review by Hisoka-X — APPROVED** [review]

**Comment by Kevintian77585** [comment]
请教下这个类的加载过程吗，本第启动后，这个downloadConnectorCache里面没有值，导致在选择任务类型后，加载不出数据源的信息
image

**Pull request merged**
