### PR TITLE
[Bug] [Seatunnel-web] GET /seatunnel/api/v1/job/executor/resource API is not using logged-in user.

### PR DESCRIPTION
**Pull request by arshadmohammad**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by arshadmohammad** [comment]
image
Exected related test case

**Review by Hisoka-X — APPROVED** [review]

**Comment by Hisoka-X** [comment]
Please fix conflict

**Comment by arshadmohammad** [comment]
resolving the problems

**Comment by arshadmohammad** [comment]
Resolved the conflics. But I think the conflict will popup again in this PR after https://github.com/apache/seatunnel-web/pull/194 is merged.

**Review by Hisoka-X — APPROVED** [review]

**Comment by arshadmohammad** [comment]
Resolved conflicts.

**Review by Hisoka-X — APPROVED** [review]

**Comment by arshadmohammad** [comment]
Thanks @Hisoka-X for reviewing and merging the PR.

**Pull request merged**
