### PR TITLE
[Feature][Seatunnel-web]Add support to configure placeholder with default value in the job config.

### PR DESCRIPTION
**Pull request by arshadmohammad**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by arshadmohammad** [comment]
The primary modification in this Pull Request focuses on org.apache.seatunnel.app.utils.JobUtils#replaceJobConfigPlaceholders and its application. 
I am currently encountering an issue when ${configParam:default} is set in the job configuration. 
The ConfigFactory.parseString(jobConfigString) operation fails with the error: 
String: 1: Token not allowed in path expression: ':' (you can double-quote this token if you really want it here).

I plan to investigate the variable substitution implementation on the Seatunnel engine side.

**Comment by arshadmohammad** [comment]
Executed integration tests, all are passed
image

Manually tested conditional query
image

**Review by Hisoka-X — APPROVED** [review]
LGTM. Thanks @arshadmohammad !

**Comment by arshadmohammad** [comment]
Thanks @Hisoka-X for reviewing and merging the PR.

**Pull request merged**
