### PR TITLE
[Improve] Add "download_datasource.sh" for downloading datasource.

### PR DESCRIPTION
**Pull request by FlechazoW**
## Purpose of this pull request

Add "download_datasource.sh" for downloading datasource.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by FlechazoW** [comment]
image

**Review by EricJoy2048 — APPROVED** [review]

**Comment by tangwenfei123** [comment]
SeaTunnel cannot select source name

**Comment by andyliumathematics** [comment]
i downloaded them and put them in apache-seatunnel-web-1.0.0-bin/libs，but when i select source name/database ... they are blank.why?

**Comment by ZhaoChenColin** [comment]
> i downloaded them and put them in apache-seatunnel-web-1.0.0-bin/libs，but when i select source name/database ... they are blank.why? 

I have the same problem, did you find out a solution?

**Comment by pertel-chen** [comment]
I have the same problem, did you find out a solution?

**Comment by WeiBiCheng** [comment]
I have the same problem, did you find out a solution?
WechatIMG25
image

**Comment by forward-seen** [comment]
> i downloaded them and put them in apache-seatunnel-web-1.0.0-bin/libs，but when i select source name/database ... they are blank.why? 

After you add  jar packages , you need to restart the web, however, the process did not close when I used the stop parameter, I manually killed the process and the problem was solved after restart.

```
sh bin/seatunnel-backend-daemon.sh stop # 这个命令并没有正常关闭
kill -9 `lsof -ti:8801` # 使用这个命令才行
```

**Comment by forward-seen** [comment]
> I have the same problem, did you find out a solution? WechatIMG25 image


After you add  jar packages , you need to restart the web, however, the process did not close when I used the stop parameter, I manually killed the process and the problem was solved after restart.

```
sh bin/seatunnel-backend-daemon.sh stop # 这个命令并没有正常关闭
kill -9 `lsof -ti:8801` # 使用这个命令才行
```

**Pull request merged**
