### PR TITLE
[IMPROVE] Add plugin isolation function

### PR DESCRIPTION
**Pull request by zhangchengming601**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Review by davidzollo — CHANGES_REQUESTED** [review]
good job
Licenses don't pass the check script, please update or add the related licenses, the detail are as follows,
image

**Comment by zhangchengming601** [comment]
> good job Licenses don't pass the check script, please update or add the related licenses, the detail are as follows, image

done

**Comment by zhangchengming601** [comment]
> good job Licenses don't pass the check script, please update or add the related licenses, the detail are as follows, image

done

**Review by davidzollo — APPROVED** [review]
+1
LGTM

**Pull request merged**
