### PR TITLE
[Bug] [Seatunnel-web] Tasks pagination is not working

### PR DESCRIPTION
**Pull request by BilwaST**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by BilwaST** [comment]
Pagination doesn't work unless you declare the MyBatisPlusInterceptor class as a Spring Bean and add the PaginationInnerInterceptor class defined with database type as an inner interceptor

**Comment by bilst-visa** [comment]
Test Report:
image

image

**Comment by BilwaST** [comment]
@arshadmohammad Can you please review this?

**Review by arshadmohammad — APPROVED** [review]
LGTM +1

**Pull request merged**
